export default data = [
  {
    id:'1',
    name: 'Tung1',
    img: 'ad.jpg',
    dateBooking: '14 phút',
    phone: '08666601699',
    result: 'đang chờ nhận',
  },
  {
    id:'2',
    name: 'Tung2',
    img: 'ad.jpg',
    dateBooking: '14 phút',
    phone: '08666601699',
    result: 'đã nhận',
  },
  {
    id:'3',
    name: 'Tung3',
    img: 'ad.jpg',
    dateBooking: '14 phút',
    phone: '08666601699',
    result: 'đang chờ nhận',
  },
  {
    id:'4',
    name: 'Tung4',
    img: 'ad.jpg',
    dateBooking: '14 phút',
    phone: '08666601699',
    result: 'đang chờ nhận',
  },
  {
    id:'5',
    name: 'Tung5',
    img: 'ad.jpg',
    dateBooking: '14 phút',
    phone: '08666601699',
    result: 'hủy',
  },
];
